import { StyleSheet } from 'react-native';

export const Colors = {
  primary: '#6B4EFF',
  primaryLight: '#EDE9FE',
  white: '#FFFFFF',
  background: '#F5F5F5',
  textPrimary: '#333333',
  textSecondary: '#666666',
  border: '#E0E0E0',
  disabled: '#BBBBBB',
};

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  statusBar: { backgroundColor: Colors.primaryLight },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.primary,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  backButton: { marginRight: 12 },
  headerTitle: { color: Colors.white, fontSize: 18, fontWeight: '600' },
  mapWrapper: { flex: 1 },
  map: { flex: 1 },
  refreshButton: {
    position: 'absolute',
    bottom: 16,
    right: 16,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: Colors.white,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
  },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  loadingText: { marginTop: 12, color: Colors.textSecondary, fontSize: 14 },
  footer: {
    backgroundColor: Colors.white,
    padding: 20,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
  },
  addressText: {
    fontSize: 18,
    fontWeight: '700',
    color: Colors.textPrimary,
    textAlign: 'center',
    marginBottom: 6,
  },
  guideText: {
    fontSize: 13,
    color: Colors.textSecondary,
    textAlign: 'center',
    marginBottom: 16,
    lineHeight: 20,
  },
  confirmButton: {
    backgroundColor: Colors.primary,
    borderRadius: 8,
    paddingVertical: 14,
    alignItems: 'center',
  },
  confirmButtonDisabled: { backgroundColor: Colors.disabled },
  confirmButtonText: { color: Colors.white, fontSize: 16, fontWeight: '600' },
});
