import { StyleSheet } from 'react-native';

export const C = {
  purple: '#8B5CF6',
  purpleDark: '#7C3AED',
  purpleLight: '#EDE9FE',
  purpleBorder: '#C4B5FD',
  white: '#FFFFFF',
  background: '#F9F8FF',
  text: '#1F1435',
  textSub: '#6B7280',
  placeholder: '#A78BFA',
  verified: '#059669',
  error: '#DC2626',
  inputBorder: '#DDD6FE',
  disabled: '#C4B5FD',
};

export const signUpStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: C.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 52,
    paddingHorizontal: 20,
    paddingBottom: 16,
    backgroundColor: C.purple,
  },
  backButton: {
    padding: 4,
  },
  backText: {
    fontSize: 24,
    color: C.white,
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 18,
    fontWeight: 'bold',
    color: C.white,
    marginRight: 32,
  },
  scrollContent: {
    paddingHorizontal: 24,
    paddingBottom: 48,
  },
  label: {
    fontSize: 13,
    color: C.purpleDark,
    marginBottom: 6,
    marginTop: 20,
    fontWeight: '600',
  },
  textInput: {
    flex: 1,
    backgroundColor: C.white,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    color: C.text,
    borderWidth: 1.5,
    borderColor: C.inputBorder,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  actionButton: {
    backgroundColor: C.purple,
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 76,
  },
  actionButtonText: {
    color: C.white,
    fontSize: 13,
    fontWeight: 'bold',
  },
  genderRow: {
    flexDirection: 'row',
    gap: 12,
  },
  genderButton: {
    flex: 1,
    backgroundColor: C.white,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: C.inputBorder,
  },
  genderButtonSelected: {
    backgroundColor: C.purple,
    borderColor: C.purple,
  },
  genderButtonText: {
    fontSize: 16,
    color: C.textSub,
    fontWeight: '600',
  },
  genderButtonTextSelected: {
    color: C.white,
  },
  selectButton: {
    backgroundColor: C.white,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderWidth: 1.5,
    borderColor: C.inputBorder,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  selectButtonDisabled: {
    backgroundColor: C.purpleLight,
    borderColor: C.purpleBorder,
  },
  selectButtonText: {
    fontSize: 16,
    color: C.text,
  },
  selectPlaceholder: {
    fontSize: 16,
    color: C.placeholder,
  },
  selectArrow: {
    fontSize: 12,
    color: C.purple,
  },
  submitButton: {
    backgroundColor: C.purple,
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 32,
  },
  submitButtonDisabled: {
    backgroundColor: C.disabled,
  },
  submitButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: C.white,
  },
  verifiedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 5,
    gap: 3,
  },
  verifiedText: {
    fontSize: 12,
    color: C.verified,
    fontWeight: '500',
  },
  profileWrapper: {
    alignSelf: 'center',
    marginTop: 24,
    marginBottom: 4,
  },
  profileImage: {
    width: 90,
    height: 90,
    borderRadius: 45,
    borderWidth: 2.5,
    borderColor: C.purple,
  },
  profilePlaceholder: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: C.purpleLight,
    borderWidth: 2,
    borderColor: C.purpleBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileIcon: {
    fontSize: 26,
  },
  profilePlaceholderText: {
    fontSize: 10,
    color: C.purpleDark,
    marginTop: 4,
  },
  profileBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: C.purple,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: C.white,
  },
  profileBadgeText: {
    color: C.white,
    fontSize: 16,
    fontWeight: 'bold',
    lineHeight: 20,
  },
  // Modal
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
  },
  modalSheet: {
    backgroundColor: C.white,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '60%',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: C.inputBorder,
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: C.text,
  },
  modalCloseText: {
    fontSize: 14,
    color: C.purple,
    fontWeight: '600',
  },
  optionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: C.purpleLight,
  },
  optionText: {
    fontSize: 16,
    color: C.text,
  },
  optionTextSelected: {
    color: C.purple,
    fontWeight: '600',
  },
  optionCheck: {
    fontSize: 16,
    color: C.purple,
  },
});
